apiVersion: apps/v1
kind: Deployment
metadata:
  name: 312-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: cithit/roseaw:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: nfs-storage
              mountPath: /mnt/data
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: roseaw-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer 
  loadBalancerIP: 10.48.10.116                                     
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: flask

