apiVersion: v1
kind: PersistentVolume
metadata:
  name: roseaw-9-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path:  /srv/nfs/roseaw         #local reference
    server: 10.48.10.140
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: roseaw-9-pvc    #claim name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: cithit/roseaw:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfs       #local mount name
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: roseaw-9-pvc    #claim
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer 
  loadBalancerIP: 10.48.10.116                                     
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: flask
